on: ["push", "pull_request"]
name: Test Coverage
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: npm install
      run: npm install
    - name: run tests
      run: npm test || true
    - name: Generate coverage report
      run: npx c8 report --reporter=lcov
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.6
      with:
        path-to-lcov: ./coverage/lcov.info
